name: Bug Report
description: File a bug report
title: '[Bug]: '
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: 'A bug happened!'
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Grafana Version
      description: On which version you are experiencing the isse?
      placeholder: ex. 10.0.0, 9.5.7
    validations:
      required: true
  - type: dropdown
    id: datasource
    attributes:
      label: on which datasource, if applicable, are you experiencing the issue with?
      multiple: true
      options:
        - Loki
        - Prometheus
        - Elasticsearch
        - Graphite
        - None of the above (please specify in the next field)
        - Not applicable (i'm not using any datasource or query in this page)
    validations:
      required: true
  - type: input
    id: ds
    attributes:
      label: Other datasources
      description: Please specify the datasource if not listed above
      placeholder: ex. some-community-plugin
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: sh
